In [1]:
import numpy as np
# Create a numpy array with shape (10, 3) filled with random integers
my_array = np.random.randint(0, 100, size=(10, 3))

# Print the array
print(my_array)


[[81 88 88]
 [93 21 99]
 [58 62 33]
 [40 97 98]
 [ 6 45 15]
 [11 53 17]
 [98 61 63]
 [82 60 57]
 [46 35  8]
 [67  7 28]]
